import { withBasePath } from "./paths";

export const primaryLinks = [
  {
    title: "Upcoming Events",
    href: withBasePath("/events"),
    description: "Chapter meeting dates and retiree breakfast gatherings.",
  },
  {
    title: "By-laws",
    href: withBasePath("/by-laws"),
    description: "A dedicated button for the retiree chapter by-laws.",
  },
  {
    title: "RHTF Documents",
    href: withBasePath("/by-laws#rhtf-documents"),
    description: "Retirees Health Trust Fund forms, policy, and agreements.",
    image: withBasePath("/rhtf.png"),
  },
  {
    title: "Health Links for Seniors",
    href: withBasePath("/health-links"),
    description: "Government and health resources gathered for members.",
  },
  {
    title: "Memorial",
    href: withBasePath("/memorial"),
    description: "A respectful place for obituaries and remembered members.",
  },
  {
    title: "Retiree Executive",
    href: withBasePath("/executive"),
    description:
      "A dedicated place for executive names, positions, and photos.",
  },
  {
    title: "Photo Gallery",
    href: withBasePath("/gallery"),
    description: "Chapter history photos with room for captions.",
  },
  {
    title: "Document Center",
    href: withBasePath("/documents"),
    description: "Documents currently approved for the website.",
  },
  {
    title: "History",
    href: withBasePath("/history"),
    description: "Photos and notes from the chapter's past.",
  },
];

export const chapterMeetings = [
  {
    date: "September 14, 2026",
    place: "Union Hall on Grant",
    doors: "Doors open at 9:00 a.m.",
    starts: "Meeting starts at 10:00 a.m.",
  },
  {
    date: "December 8, 2026",
    place: "Caboto Centre",
    doors: "Doors open at 9:00 a.m.",
    starts: "Meeting starts at 10:00 a.m.",
  },
];

export const retireeBreakfasts = [
  {
    date: "October 7, 2026",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "A-159 Meadowood Drive, Winnipeg",
  },
  {
    date: "October 21, 2026",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "Pembina Hwy & Kirkbridge, Winnipeg",
  },
  {
    date: "November 4, 2026",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "Garden City Shopping Centre, Winnipeg",
  },
  {
    date: "November 18, 2026",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "1629 Kenaston Blvd, Winnipeg",
  },
  {
    date: "December 2, 2026",
    venue: "Altos - Canad Inns",
    time: "9:00-11:00 a.m.",
    location: "1405 St. Matthew's Ave, Winnipeg",
  },
  {
    date: "December 16, 2026",
    venue: "Altos - Canad Inns",
    time: "9:00-11:00 a.m.",
    location: "1405 St. Matthew's Ave, Winnipeg",
  },
  {
    date: "January 6, 2027",
    venue: "Altos - Canad Inns",
    time: "9:00-11:00 a.m.",
    location: "1405 St. Matthew's Ave, Winnipeg",
  },
  {
    date: "January 20, 2027",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "Pembina Hwy & Kirkbridge, Winnipeg",
  },
  {
    date: "February 3, 2027",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "1629 Kenaston Blvd, Winnipeg",
  },
  {
    date: "February 17, 2027",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "Garden City Shopping Centre, Winnipeg",
  },
  {
    date: "March 3, 2027",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "1629 Kenaston Blvd, Winnipeg",
  },
  {
    date: "March 17, 2027",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "Pembina Hwy & Kirkbridge, Winnipeg",
  },
  {
    date: "March 31, 2027",
    venue: "Altos - Canad Inns",
    time: "9:00-11:00 a.m.",
    location: "1405 St. Matthew's Ave, Winnipeg",
  },
  {
    date: "April 14, 2027",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "1629 Kenaston Blvd, Winnipeg",
  },
  {
    date: "April 28, 2027",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "Garden City Shopping Centre, Winnipeg",
  },
  {
    date: "May 19, 2027",
    venue: "Smitty's",
    time: "9:00-11:00 a.m.",
    location: "Pembina Hwy & Kirkbridge, Winnipeg",
  },
];

export const executiveMembers = [
  {
    name: "Orville Desjarlais",
    role: "Chairperson and Retiree Trustee for the RHTF",
    image: withBasePath("/executive/orville-desjarlais-upright-stripped.jpg"),
    width: 4896,
    height: 6528,
  },
  {
    name: "Brian Rebizant",
    role: "Financial/Recording Secretary",
    image: withBasePath("/executive/brian-rebizant.jpeg"),
    width: 640,
    height: 480,
  },
  {
    name: "Hal Pacaud",
    role: "Sergeant-at-Arms",
    image: withBasePath("/executive/hal-pacaud.jpg"),
    width: 1200,
    height: 1600,
  },
  {
    name: "Faron Edel",
    role: "Co-Chair",
    note: "Photo not yet available.",
  },
];

export const healthLinks = [
  {
    title: "City of Winnipeg E.R.I.K. Kits",
    href: "https://professionals.wrha.mb.ca/community-resources/community-support/city-of-winnipeg-erik-kits/",
    description:
      "Emergency Response Information Kits help responders find medical details quickly in an emergency.",
  },
  {
    title: "Programs and services for seniors",
    href: "https://www.canada.ca/seniors",
    description:
      "Canada.ca hub for pensions, benefits, health, caregiving, fraud prevention, and safe living resources.",
  },
  {
    title: "Aging and seniors",
    href: "https://www.canada.ca/en/public-health/services/health-promotion/aging-seniors.html",
    description:
      "Public Health Agency of Canada information on healthy aging, falls prevention, dementia, and wellbeing.",
  },
  {
    title: "Manitoba seniors resources",
    href: "https://www.gov.mb.ca/seniors/resources/housing-options-and-care-planning.html",
    description:
      "Provincial resources for home care, housing options, community supports, and planning.",
  },
];

export const memorialEntries = [
  {
    name: "Kevin Donald Baker",
    detail: "August 9, 1960 - October 20, 2024",
    group: "Passed while at work",
    image: withBasePath("/memorial/kevin-donald-baker.png"),
  },
  {
    name: "Ronald McMillian",
    detail: "Died July 21, 2017",
    group: "Passed while at work",
    image: withBasePath("/memorial/ronald-mcmillian.png"),
  },
  {
    name: "Don Broomfield",
    detail: "Died June 6, 2023",
    group: "Passed while at work",
    image: withBasePath("/memorial/don-broomfield.png"),
  },
  {
    name: "Randy Colomy",
    detail: "Died June 25, 2002",
    group: "Passed while at work",
  },
  {
    name: "Fred Epps",
    detail: "Died in 2000",
    group: "Passed while at work",
  },
  {
    name: "Graham Hardwick",
    detail: "Died January 15, 2007",
    group: "Passed while at work",
  },
  {
    name: "Len Holloway",
    detail: "Date not listed",
    group: "Passed while at work",
    image: withBasePath("/memorial/len-holloway.png"),
  },
  {
    name: 'Robert "Kip" Kipling',
    detail: "Died July 29, 2021",
    group: "Passed while at work",
    image: withBasePath("/memorial/robert-kip-kipling.png"),
  },
  {
    name: "Greg Kokotyn",
    detail: "Died November 12, 2006",
    group: "Passed while at work",
    image: withBasePath("/memorial/greg-kokotyn.png"),
  },
  {
    name: 'Ivica "John" Kucinic',
    detail: "Died March 28, 2012",
    group: "Passed while at work",
    image: withBasePath("/memorial/ivica-john-kucinic.png"),
  },
  {
    name: "Mike Lester",
    detail: "Died August 17, 2018",
    group: "Passed while at work",
    image: withBasePath("/memorial/mike-lester.png"),
  },
  {
    name: "Bill Loftus",
    detail: "Died July 24, 2005",
    group: "Passed while at work",
    image: withBasePath("/memorial/bill-loftus.png"),
  },
  {
    name: "Bill Michie",
    detail: "Died February 19, 2004",
    group: "Passed while at work",
  },
  {
    name: "Tony Rooprai",
    detail: "Died June 7, 2014",
    group: "Passed while at work",
    image: withBasePath("/memorial/tony-rooprai.png"),
  },
  {
    name: "Robert Sanchez",
    detail: "Died January 18, 2006",
    group: "Passed while at work",
    image: withBasePath("/memorial/robert-sanchez.png"),
  },
  {
    name: "Lorne Shultz",
    detail: "Died June 19, 2014",
    group: "Passed while at work",
    image: withBasePath("/memorial/lorne-shultz.png"),
  },
  {
    name: "Wayne Sobichanski",
    detail: "Died August 25, 2025",
    group: "Passed while at work",
    image: withBasePath("/memorial/wayne-sobichanski.png"),
  },
  {
    name: "Gary Stroppa",
    detail: "Died December 11, 2005",
    group: "Passed while at work",
    image: withBasePath("/memorial/gary-stroppa.png"),
  },
  {
    name: "Patrick Whiting",
    detail: "Died in 2010",
    group: "Passed while at work",
    image: withBasePath("/memorial/patrick-whiting.png"),
  },
  {
    name: "Darrell Adamik",
    detail: "Died January 19, 2019",
    group: "Retired member",
    image: withBasePath("/memorial/darrell-adamik.png"),
  },
  {
    name: "Albert Adamkowicz",
    detail: "Died June 13, 2019",
    group: "Retired member",
    image: withBasePath("/memorial/albert-adamkowicz.png"),
  },
  {
    name: "Rick Adams",
    detail: "Died January 22, 2021",
    group: "Retired member",
    image: withBasePath("/memorial/rick-adams.png"),
  },
  {
    name: "Rogelio Afroung",
    detail: "Died in 2022",
    group: "Retired member",
  },
  {
    name: "Lou Bautista",
    detail: "Died February 27, 2024",
    group: "Retired member",
    image: withBasePath("/memorial/lou-bautista.png"),
  },
  {
    name: "Ben Aquino",
    detail: "Died October 17, 2015",
    group: "Retired member",
    image: withBasePath("/memorial/ben-aquino.png"),
  },
  {
    name: "Ross Boyle",
    detail: "Died October 4, 2013",
    group: "Retired member",
    image: withBasePath("/memorial/ross-boyle.png"),
  },
  {
    name: "Rufo Cabanal",
    detail: "Died April 6, 2011",
    group: "Retired member",
    image: withBasePath("/memorial/rufo-cabanal.png"),
  },
  {
    name: "Lonnie Christensen",
    detail: "Died January 16, 2020",
    group: "Retired member",
    image: withBasePath("/memorial/lonnie-christensen.png"),
  },
  {
    name: "Marg Cyndroski",
    detail: "Died in 2018",
    group: "Retired member",
    image: withBasePath("/memorial/marg-cyndroski.png"),
  },
  {
    name: "Lou Dahle",
    detail: "Died August 14, 2001",
    group: "Retired member",
  },
  {
    name: "Barry Dickie",
    detail: "Died May 2022",
    group: "Retired member",
    image: withBasePath("/memorial/barry-dickie.png"),
  },
  {
    name: "Bill Dolinski",
    detail: "Died March 24, 2006",
    group: "Retired member",
  },
  {
    name: "Steve Borynski",
    detail: "Died May 1, 2019",
    group: "Retired member",
  },
  {
    name: "William Durant",
    detail: "Died January 2012",
    group: "Retired member",
    image: withBasePath("/memorial/william-durant.png"),
  },
  {
    name: "Walter Erbach",
    detail: "Died September 13, 2014",
    group: "Retired member",
  },
  {
    name: "Richard Hoffman",
    detail: "Died December 24, 2021",
    group: "Retired member",
    image: withBasePath("/memorial/richard-hoffman.png"),
  },
  {
    name: "Earle Hough",
    detail: "Died December 28, 2013",
    group: "Retired member",
    image: withBasePath("/memorial/earle-hough.png"),
  },
  {
    name: "Ray Huckerby",
    detail: "Died October 25, 2016",
    group: "Retired member",
    image: withBasePath("/memorial/ray-huckerby.png"),
  },
  {
    name: "Romesh Joshi",
    detail: "Died November 17, 2013",
    group: "Retired member",
    image: withBasePath("/memorial/romesh-joshi.png"),
  },
  {
    name: "Bill King",
    detail: "Died April 27, 2019",
    group: "Retired member",
    image: withBasePath("/memorial/bill-king.png"),
  },
  {
    name: "Doug Kirkness",
    detail: "Died January 6, 2022",
    group: "Retired member",
    image: withBasePath("/memorial/doug-kirkness.png"),
  },
  {
    name: "Walter Kuklinski",
    detail: "Died June 15, 2021",
    group: "Retired member",
  },
  {
    name: "Milos Lazic",
    detail: "Died January 21, 2025",
    group: "Retired member",
    image: withBasePath("/memorial/milos-lazic.png"),
  },
  {
    name: "Armin Lehn",
    detail: "Date not listed",
    group: "Retired member",
    image: withBasePath("/memorial/armin-lehn.png"),
  },
  {
    name: "Gerry Lilischkies",
    detail: "Died February 12, 2023",
    group: "Retired member",
    image: withBasePath("/memorial/gerry-lilischkies.png"),
  },
  {
    name: "John Marlow",
    detail: "Died November 9, 2012",
    group: "Retired member",
    image: withBasePath("/memorial/john-marlow.png"),
  },
  {
    name: "Tom Morgan",
    detail: "Died December 26, 2019",
    group: "Retired member",
    image: withBasePath("/memorial/tom-morgan.png"),
  },
  {
    name: "Ed Mudray",
    detail: "Died October 8, 2023",
    group: "Retired member",
    image: withBasePath("/memorial/ed-mudray.png"),
  },
  {
    name: "Paul Racz Sr",
    detail: "Died November 4, 2024",
    group: "Retired member",
    image: withBasePath("/memorial/paul-racz-sr.png"),
  },
  {
    name: "Ralph Rampersad",
    detail: "Died December 7, 2022",
    group: "Retired member",
    image: withBasePath("/memorial/ralph-rampersad.png"),
  },
  {
    name: "Helmut Raske",
    detail: "Died April 12, 2015",
    group: "Retired member",
  },
  {
    name: "Terry Rayland",
    detail: "Died June 22, 2023",
    group: "Retired member",
  },
  {
    name: "Ernesto Remoquillo",
    detail: "Died August 15, 2013",
    group: "Retired member",
    image: withBasePath("/memorial/ernesto-remoquillo.png"),
  },
  {
    name: "Germain Reuther",
    detail: "Died June 19, 2020",
    group: "Retired member",
    image: withBasePath("/memorial/germain-reuther.png"),
  },
  {
    name: "Jeff Romaniuk",
    detail: "Died April 20, 2016",
    group: "Retired member",
    image: withBasePath("/memorial/jeff-romaniuk.png"),
  },
  {
    name: "Derek Rowe",
    detail: "Died May 26, 2011",
    group: "Retired member",
  },
  {
    name: "Gordon Rusnak",
    detail: "Died February 29, 2020",
    group: "Retired member",
  },
  {
    name: "Don Schellenburg",
    detail: "Died November 2, 2017",
    group: "Retired member",
  },
  {
    name: "Renato Silva",
    detail: "Died January 28, 2025",
    group: "Retired member",
    image: withBasePath("/memorial/renato-silva.png"),
  },
  {
    name: "Ron Skwarek",
    detail: "Died December 31, 2023",
    group: "Retired member",
  },
  {
    name: "Richard Sobie",
    detail: "Died December 29, 2021",
    group: "Retired member",
    image: withBasePath("/memorial/richard-sobie.png"),
  },
  {
    name: "Barry Thompson",
    detail: "Died January 23, 2021",
    group: "Retired member",
    image: withBasePath("/memorial/barry-thompson.png"),
  },
  {
    name: "Guy Wescott",
    detail: "Died August 7, 2011",
    group: "Retired member",
    image: withBasePath("/memorial/guy-wescott.png"),
  },
  {
    name: "Gerry Wilgosh",
    detail: "Died April 9, 2023",
    group: "Retired member",
    image: withBasePath("/memorial/gerry-wilgosh.png"),
  },
  {
    name: "Lorne Wilgosh",
    detail: "Died February 8, 2024",
    group: "Retired member",
  },
  {
    name: "Roman Demczyszak",
    detail: "Died in 2023",
    group: "Retired member",
  },
  {
    name: "Wayne Fritzler",
    detail: "Died in 2011",
    group: "Retired member",
  },
  {
    name: "Joven Jobo",
    detail: "Died in 2020",
    group: "Retired member",
  },
  {
    name: "Bill Aumuller",
    detail: "Died January 8, 2008",
    group: "Remembered member",
  },
  {
    name: "Guy Black",
    detail: "Died September 22, 2003",
    group: "Remembered member",
  },
  {
    name: "Rolly Charette",
    detail: "Died February 21, 2023",
    group: "Remembered member",
  },
  {
    name: "Bruce Clark",
    detail: "Died September 28, 2022",
    group: "Remembered member",
    image: withBasePath("/memorial/bruce-clark.png"),
  },
  {
    name: "Ben Corcoran",
    detail: "Died March 4, 2004",
    group: "Remembered member",
  },
  {
    name: "Larry Elder",
    detail: "Died January 10, 2023",
    group: "Remembered member",
    image: withBasePath("/memorial/larry-elder.png"),
  },
  {
    name: "John Furi",
    detail: "Died April 5, 2007",
    group: "Remembered member",
  },
  {
    name: "Jim Gibbons",
    detail: "Died March 28, 2025",
    group: "Remembered member",
    image: withBasePath("/memorial/jim-gibbons.png"),
  },
  {
    name: "Ralph Green",
    detail: "Died September 17, 2006",
    group: "Remembered member",
  },
  {
    name: "Cecil Goulding",
    detail: "Died April 15, 2009",
    group: "Remembered member",
    image: withBasePath("/memorial/cecil-goulding.png"),
  },
  {
    name: "Walter Kozak",
    detail: "Died February 26, 2012",
    group: "Remembered member",
    image: withBasePath("/memorial/walter-kozak.png"),
  },
  {
    name: "Gerry Licorish",
    detail: "Died May 6, 2013",
    group: "Remembered member",
    image: withBasePath("/memorial/gerry-licorish.png"),
  },
  {
    name: "Tony Lima",
    detail: "Died March 18, 2006",
    group: "Remembered member",
    image: withBasePath("/memorial/tony-lima.png"),
  },
  {
    name: "Ram Rambaran",
    detail: "Died October 30, 2015",
    group: "Remembered member",
    image: withBasePath("/memorial/ram-rambaran.png"),
  },
  {
    name: "Henry Rice",
    detail: "Date not listed",
    group: "Remembered member",
    image: withBasePath("/memorial/henry-rice.png"),
  },
  {
    name: "Bill Turney",
    detail: "Died September 10, 1999",
    group: "Remembered member",
  },
  {
    name: "Reynaldo de Castro",
    detail: "March 11, 1947 - March 27, 2026",
    group: "Retired member",
    image: withBasePath("/memorial/rey-de-castro.jpg"),
  },
];

export const rhtfDocuments = [
  {
    title: "Retiree By-laws",
    href: withBasePath("/documents/retiree-by-laws.pdf"),
    description: "Main chapter by-laws document.",
  },
  {
    title: "RHTF Policy",
    href: withBasePath("/documents/rhtf-policy.pdf"),
    description: "The most recent retiree handbook policy.",
  },
  {
    title: "RHTF Claim Form",
    href: withBasePath("/documents/rhtf-claim-form.pdf"),
    description: "Current RHTF claim form in use for chapter support.",
  },
  {
    title: "Retiree Registration Form",
    href: withBasePath("/documents/retiree-registration-form.pdf"),
    description: "Registration and membership form for chapter filing.",
  },
  {
    title: "Amended RHTF Trust Agreement",
    href: withBasePath("/documents/rhtf/amended-rhtf-trust-agreement.pdf"),
    description: "Signed amendment package for the trust agreement.",
  },
  {
    title: "Amendment 1 (P1)",
    href: withBasePath("/documents/rhtf/amendment-1-p1.png"),
    description: "First page of RHTF amendment 1.",
  },
  {
    title: "Amendment 1 (P2)",
    href: withBasePath("/documents/rhtf/amendment-1-p2.png"),
    description: "Second page of RHTF amendment 1.",
  },
  {
    title: "Amendment 2 (P1)",
    href: withBasePath("/documents/rhtf/amendment-2-p1.png"),
    description: "First page of RHTF amendment 2.",
  },
  {
    title: "Amendment 2 (P2)",
    href: withBasePath("/documents/rhtf/amendment-2-p2.png"),
    description: "Second page of RHTF amendment 2.",
  },
  {
    title: "Signed Trust Agreement",
    href: withBasePath("/documents/rhtf/signed-trust-agreement.pdf"),
    description: "Signed copy of the trust agreement document.",
  },
];

export const historyHighlights = [
  {
    title: "Christmas Luncheon",
    image: withBasePath("/1000009773.jpg"),
    caption: "A chapter gathering from the history archive.",
  },
  {
    title: "Retiree Chapter Photos",
    image: withBasePath("/1000009772.jpg"),
    caption: "Images collected for the history section.",
  },
  {
    title: "Strike History",
    image: withBasePath("/scan_260131-102931_1.jpg"),
    caption: "Scanned material from the chapter history files.",
  },
];

export const additionalHistoryDocuments = [
  {
    title: "Retiree Group 2026",
    href: withBasePath("/documents/history/retiree-group-2026.png"),
    description: "Christmas Luncheon 2025 group photo.",
    width: 1153,
    height: 367,
  },
  {
    title: "Donation Table",
    href: withBasePath("/documents/history/donation-table.png"),
    description: "Christmas Luncheon 2025 donation table photo.",
    width: 864,
    height: 1184,
  },
  {
    title: "2024 Retirees Luncheon",
    href: withBasePath("/documents/history/2024-retirees-luncheon.jpg"),
    description: "Luncheon group shot from 2024.",
    width: 3024,
    height: 4032,
  },
  {
    title: "Strike Scan 1",
    href: withBasePath("/documents/history/scan-260131-102725-1.jpg"),
    description: "Strikes archive scan and annotation.",
    width: 2296,
    height: 3287,
  },
  {
    title: "Strike Screenshot 1",
    href: withBasePath("/documents/history/strikes-3-04-17-pm.png"),
    description: "Strikes archive screenshot.",
    width: 726,
    height: 543,
  },
  {
    title: "Strike Screenshot 2",
    href: withBasePath("/documents/history/strikes-3-04-54-pm.png"),
    description: "Strikes archive screenshot.",
    width: 879,
    height: 567,
  },
  {
    title: "Strike Scan 2",
    href: withBasePath("/documents/history/scan-260131-102830-1.jpg"),
    description: "Strikes archive scan and annotation.",
    width: 3155,
    height: 2511,
  },
  {
    title: "Strike Screenshot 3",
    href: withBasePath("/documents/history/strikes-3-05-50-pm.png"),
    description: "Strikes archive screenshot.",
    width: 1230,
    height: 879,
  },
];

export const recentHistoryPhotos = [
  {
    title: "History Photo 1000010553",
    href: withBasePath("/1000010553.png"),
    width: 791,
    height: 494,
  },
  {
    title: "History Photo 1000010554",
    href: withBasePath("/1000010554.png"),
    width: 790,
    height: 494,
  },
  {
    title: "History Photo 1000010555",
    href: withBasePath("/1000010555.png"),
    width: 790,
    height: 494,
  },
  {
    title: "History Photo 1000010556",
    href: withBasePath("/1000010556.png"),
    width: 790,
    height: 494,
  },
  {
    title: "History Photo 1000010557",
    href: withBasePath("/1000010557.png"),
    width: 790,
    height: 494,
  },
  {
    title: "History Photo 1000010558",
    href: withBasePath("/1000010558.png"),
    width: 790,
    height: 494,
  },
  {
    title: "History Photo 1000010559",
    href: withBasePath("/1000010559.png"),
    width: 790,
    height: 485,
  },
  {
    title: "History Photo 1000010560",
    href: withBasePath("/1000010560.png"),
    width: 791,
    height: 484,
  },
  {
    title: "History Photo 1000010561",
    href: withBasePath("/1000010561.png"),
    width: 790,
    height: 485,
  },
  {
    title: "History Photo 1000010562",
    href: withBasePath("/1000010562.png"),
    width: 790,
    height: 484,
  },
  {
    title: "History Photo 1000010563",
    href: withBasePath("/1000010563.png"),
    width: 790,
    height: 484,
  },
  {
    title: "History Photo 1000010564",
    href: withBasePath("/1000010564.png"),
    width: 790,
    height: 484,
  },
  {
    title: "History Photo 1000010565",
    href: withBasePath("/1000010565.png"),
    width: 791,
    height: 485,
  },
  {
    title: "History Photo 1000010566",
    href: withBasePath("/1000010566.png"),
    width: 790,
    height: 484,
  },
  {
    title: "History Photo 1000010567",
    href: withBasePath("/1000010567.png"),
    width: 821,
    height: 484,
  },
  {
    title: "History Photo 1000010568",
    href: withBasePath("/1000010568.png"),
    width: 822,
    height: 484,
  },
  {
    title: "History Photo 1000010569",
    href: withBasePath("/1000010569.png"),
    width: 822,
    height: 441,
  },
  {
    title: "History Photo 1000010570",
    href: withBasePath("/1000010570.png"),
    width: 822,
    height: 501,
  },
  {
    title: "History Photo 1000010571",
    href: withBasePath("/1000010571.png"),
    width: 1221,
    height: 715,
  },
  {
    title: "History Photo 1000010572",
    href: withBasePath("/1000010572.png"),
    width: 1125,
    height: 642,
  },
  {
    title: "History Photo 1000010573",
    href: withBasePath("/1000010573.png"),
    width: 1106,
    height: 795,
  },
  {
    title: "History Photo 1000010574",
    href: withBasePath("/1000010574.png"),
    width: 1138,
    height: 795,
  },
  {
    title: "History Photo 1000010575",
    href: withBasePath("/1000010575.png"),
    width: 536,
    height: 421,
  },
  {
    title: "History Photo 1000010576",
    href: withBasePath("/1000010576.png"),
    width: 536,
    height: 421,
  },
  {
    title: "History Photo 1000010577",
    href: withBasePath("/1000010577.png"),
    width: 536,
    height: 421,
  },
  {
    title: "History Photo 1000010578",
    href: withBasePath("/1000010578.png"),
    width: 561,
    height: 434,
  },
  {
    title: "History Photo 1000010579",
    href: withBasePath("/1000010579.png"),
    width: 532,
    height: 392,
  },
  {
    title: "History Photo 1000010580",
    href: withBasePath("/1000010580.png"),
    width: 546,
    height: 418,
  },
  {
    title: "History Photo 1000010581",
    href: withBasePath("/1000010581.png"),
    width: 546,
    height: 505,
  },
  {
    title: "History Photo 1000010582",
    href: withBasePath("/1000010582.png"),
    width: 583,
    height: 523,
  },
  {
    title: "History Photo 1000010583",
    href: withBasePath("/1000010583.png"),
    width: 582,
    height: 472,
  },
  {
    title: "History Photo 1000010584",
    href: withBasePath("/1000010584.png"),
    width: 1132,
    height: 620,
  },
  {
    title: "History Photo 1000010585",
    href: withBasePath("/1000010585.png"),
    width: 558,
    height: 404,
  },
  {
    title: "History Photo 1000010586",
    href: withBasePath("/1000010586.png"),
    width: 558,
    height: 428,
  },
  {
    title: "History Photo 1000010587",
    href: withBasePath("/1000010587.png"),
    width: 558,
    height: 428,
  },
  {
    title: "History Photo 1000010588",
    href: withBasePath("/1000010588.png"),
    width: 558,
    height: 428,
  },
  {
    title: "History Photo 1000010589",
    href: withBasePath("/1000010589.png"),
    width: 557,
    height: 634,
  },
  {
    title: "History Photo 1000010590",
    href: withBasePath("/1000010590.png"),
    width: 557,
    height: 670,
  },
  {
    title: "History Photo 1000010591",
    href: withBasePath("/1000010591.png"),
    width: 558,
    height: 483,
  },
  {
    title: "History Photo 1000010592",
    href: withBasePath("/1000010592.png"),
    width: 841,
    height: 521,
  },
  {
    title: "History Photo 1000010593",
    href: withBasePath("/1000010593.png"),
    width: 567,
    height: 811,
  },
  {
    title: "History Photo 1000010594",
    href: withBasePath("/1000010594.png"),
    width: 567,
    height: 410,
  },
  {
    title: "History Photo 1000010595",
    href: withBasePath("/1000010595.png"),
    width: 567,
    height: 477,
  },
  {
    title: "History Photo 1000010596",
    href: withBasePath("/1000010596.png"),
    width: 542,
    height: 725,
  },
  {
    title: "History Photo 1000010597",
    href: withBasePath("/1000010597.png"),
    width: 559,
    height: 357,
  },
  {
    title: "History Photo 1000010598",
    href: withBasePath("/1000010598.png"),
    width: 1123,
    height: 718,
  },
  {
    title: "History Photo 1000010599",
    href: withBasePath("/1000010599.png"),
    width: 545,
    height: 466,
  },
  {
    title: "History Photo 1000010600",
    href: withBasePath("/1000010600.png"),
    width: 554,
    height: 400,
  },
  {
    title: "History Photo 1000010605",
    href: withBasePath("/1000010605.png"),
    width: 519,
    height: 242,
  },
];

export const orvilleHistoryPhotos = [
  {
    title: "History Photo 1000010601",
    href: withBasePath("/history/orville-may-2026/1000010601.png"),
    width: 1148,
    height: 805,
  },
  {
    title: "History Photo 1000010602",
    href: withBasePath("/history/orville-may-2026/1000010602.png"),
    width: 580,
    height: 805,
  },
  {
    title: "History Photo 1000010603",
    href: withBasePath("/history/orville-may-2026/1000010603.png"),
    width: 544,
    height: 400,
  },
  {
    title: "History Photo 1000010604",
    href: withBasePath("/history/orville-may-2026/1000010604.png"),
    width: 842,
    height: 379,
  },
  {
    title: "History Photo 1000010606",
    href: withBasePath("/history/orville-may-2026/1000010606.png"),
    width: 556,
    height: 576,
  },
  {
    title: "History Photo 1000010607",
    href: withBasePath("/history/orville-may-2026/1000010607.png"),
    width: 537,
    height: 441,
  },
  {
    title: "History Photo 1000010608",
    href: withBasePath("/history/orville-may-2026/1000010608.png"),
    width: 538,
    height: 441,
  },
  {
    title: "History Photo 1000010609",
    href: withBasePath("/history/orville-may-2026/1000010609.png"),
    width: 1129,
    height: 788,
  },
  {
    title: "History Photo 1000010610",
    href: withBasePath("/history/orville-may-2026/1000010610.png"),
    width: 555,
    height: 440,
  },
  {
    title: "History Photo 1000010611",
    href: withBasePath("/history/orville-may-2026/1000010611.png"),
    width: 556,
    height: 310,
  },
  {
    title: "History Photo 1000010612",
    href: withBasePath("/history/orville-may-2026/1000010612.png"),
    width: 1136,
    height: 460,
  },
  {
    title: "History Photo 1000010613",
    href: withBasePath("/history/orville-may-2026/1000010613.png"),
    width: 1172,
    height: 801,
  },
  {
    title: "History Photo 1000010614",
    href: withBasePath("/history/orville-may-2026/1000010614.png"),
    width: 542,
    height: 441,
  },
  {
    title: "History Photo 1000010615",
    href: withBasePath("/history/orville-may-2026/1000010615.png"),
    width: 535,
    height: 403,
  },
  {
    title: "History Photo 1000010618",
    href: withBasePath("/history/orville-may-2026/1000010618.png"),
    width: 1125,
    height: 463,
  },
  {
    title: "History Photo 1000010619",
    href: withBasePath("/history/orville-may-2026/1000010619.png"),
    width: 813,
    height: 441,
  },
  {
    title: "History Photo 1000010620",
    href: withBasePath("/history/orville-may-2026/1000010620.png"),
    width: 813,
    height: 441,
  },
];
